/* Generated by re2c 3.0 on Wed Dec  6 19:24:37 2023 */
#line 1 "_gen/synthetic-rsc-10.re2c.cc"

#line 5 "_gen/synthetic-rsc-10.cc"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 30) YYFILL(30);
	yych = *YYCURSOR;
	switch (yych) {
		case 'a': goto yy3;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 6 "_gen/synthetic-rsc-10.re2c.cc"
	{
    printf("no\n");
  }
#line 21 "_gen/synthetic-rsc-10.cc"
yy3:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '?': goto yy4;
		default: goto yy2;
	}
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy6;
		default: goto yy5;
	}
yy5:
	YYCURSOR = YYMARKER;
	goto yy2;
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy7;
		default: goto yy5;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy8;
		default: goto yy5;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy9;
		default: goto yy5;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy10;
		default: goto yy5;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy11;
		default: goto yy5;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy12;
		default: goto yy5;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy13;
		default: goto yy5;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy14;
		default: goto yy5;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy15;
		default: goto yy5;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy16;
		default: goto yy5;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy17;
		default: goto yy5;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy18;
		default: goto yy5;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy19;
		default: goto yy5;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy20;
		default: goto yy5;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy21;
		default: goto yy5;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy22;
		default: goto yy5;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case '?': goto yy23;
		default: goto yy5;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy24;
		default: goto yy5;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy25;
		default: goto yy5;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy26;
		default: goto yy5;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy27;
		default: goto yy5;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy28;
		default: goto yy5;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy29;
		default: goto yy5;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy30;
		default: goto yy5;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy31;
		default: goto yy5;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy32;
		default: goto yy5;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy33;
		default: goto yy5;
	}
yy33:
	++YYCURSOR;
#line 3 "_gen/synthetic-rsc-10.re2c.cc"
	{
    printf("yes\n");
  }
#line 205 "_gen/synthetic-rsc-10.cc"
}
#line 10 "_gen/synthetic-rsc-10.re2c.cc"

